server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false   # false表示不想注册中心注册自己

    fetch-registry: false          # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

    service-url:
      # 设置与 eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版
      defaultZone:  http://eureka7002.com:7002/eureka/    #集群
    #  server:
    #    # 关闭自我保护机制
    #    enable-self-preservation: false
    #    # 心跳时间默认90s，改为2000ms，即2s
    #    eviction-interval-timer-in-ms: 2000
